---
abstract: 'Test that dependencies are properly listed for your dist'
author:
  - 'Matthew Horsfall (alh) <WolfSage@gmail.com>'
build_requires:
  Test::DescribeMe: 0
  Test::Exception: 0
  Test::More: 0.88
  Test::Pod: 1.00
configure_requires:
  ExtUtils::MakeMaker: 6.30
  strict: 0
  warnings: 0
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.005, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Dependencies
requires:
  CPAN::Meta: 0
  Carp: 0
  Cwd: 0
  Data::Dumper: 0
  Exporter: 0
  Module::CoreList: 0
  PPI: 0
  Perl::PrereqScanner: 0
  Test::DescribeMe: 0
  Test::More: 0.88
  Test::Pod: 1.00
  strict: 0
  version: 0.77
  warnings: 0
version: 0.002
